# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main","dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build project
        uses: gradle/wrapper-action@v2
        with:
          tasks: 'clean assembleDebug'
      - name: Run unit tests
        uses: gradle/wrapper-action@v2
        with:
          tasks: 'test'
      - name: SonarQube analysis
        uses: SonarSource/sonarqube-scan-action@v1
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      - name: Deploy to Play Store
        uses: ruby-android/ruby-android-playstore-deploy@v1
        env:
          TRACK: 'internal'
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}



